Integrate with VTune JIT Profiling API
fleroviux/lunatic pull request #39
Opened 2022-04-17 00:40 UTC by StrikerX3

Closes #37.

2022-04-17 20:21 UTC, fleroviux requested changes

2022-04-17 20:21 UTC, fleroviux commented on src/backend/x86_64/backend.cpp
> +#if LUNATIC_USE_VTUNE
Can this be moved into a separate method? That method is already a way too complex and I'd like to not make it bigger than it already is.

2022-04-17 20:21 UTC, fleroviux commented on test/main.cpp
> +#ifdef _WIN32
Why is this necessary? I don't think I ever had to manually add those libs in the past.

2022-04-17 21:39 UTC, StrikerX3 commented on test/main.cpp
> +#ifdef _WIN32
Not sure why, but in my system it will refuse to link if I don't specify those libraries. Perhaps differences in the build systems we use?

I'm using VS 2022 and SDL2 from vcpkg, if that helps.

2022-04-17 21:39 UTC, StrikerX3 commented on src/backend/x86_64/backend.cpp
> +#if LUNATIC_USE_VTUNE
Will do.

2022-04-22 19:28 UTC, fleroviux commented
LGTM

2022-04-22 19:28 UTC, merged